### ISSUE TITLE
/Desktop/EasyApplyBot-master/main.py:16: DeprecationWarning: executable_path has been deprecated,

### ISSUE THREAD

**Issue by logix727** [madingess/EasyApplyBot#3]
home//Desktop/EasyApplyBot-master/main.py:16: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install(), chrome_options=browser_options)
/home//Desktop/EasyApplyBot-master/main.py:16: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(ChromeDriverManager().install(), chrome_options=browser_options)

**Comment by madingess** [comment]
This looks to be a warning and not impacting application behavior. Nonetheless, it does not appear when I run this locally.

Since there have been a number of issues arise related to varying package and python versions, I added a virtual environment to the project tracking. Will you please try again using the updated [Setup & Startup section of the README](https://github.com/madingess/EasyApplyBot/blob/master/README.md#setup--startup) to see if this issue persists?

**Comment by madingess** [comment]
Closing this. Please reopen if issue persists.
